<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateResidentialsTable extends Migration
{

    protected $primaryKey = 'listingkeynumeric';

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('residentials', function (Blueprint $table) {
            $table->integer('listingkeynumeric');
            $table->text('accessibilityfeatures')->nullable();
            $table->text('additionalparcelsdescription')->nullable();
            $table->boolean('additionalparcelsyn')->nullable();
            $table->string('adnumber', 15)->nullable();
            $table->text('appliances')->nullable();
            $table->boolean('appliancesyn')->nullable();
            $table->text('architecturalstyle')->nullable();
            $table->string('assessments', 68)->nullable();
            $table->boolean('assessmentsyn')->nullable();
            $table->text('associationamenities')->nullable();
            $table->decimal('associationfee',14,2)->nullable();
            $table->decimal('associationfee2',14,2)->nullable();
            $table->string('associationfee2frequency', 25)->nullable();
            $table->string('associationfeefrequency', 25)->nullable();
            $table->string('associationmanagementname', 50)->nullable();
            $table->string('associationmanagementname2', 50)->nullable();
            $table->string('associationname', 50)->nullable();
            $table->string('associationname2', 50)->nullable();
            $table->boolean('associationyn')->nullable();
            $table->boolean('attachedgarageyn')->nullable();
            $table->text('basement')->nullable();
            $table->integer('bathroomsfull')->nullable();
            $table->integer('bathroomsfullandthreequarter')->nullable();
            $table->integer('bathroomshalf')->nullable();
            $table->integer('bathroomsonequarter')->nullable();
            $table->integer('bathroomsthreequarter')->nullable();
            $table->integer('bathroomstotalinteger')->nullable();
            $table->integer('bedroomstotal')->nullable();
            $table->decimal('belowgradefinishedarea',14,2)->nullable();
            $table->string('belowgradefinishedareaunits', 25)->nullable();
            $table->string('buildermodel', 50)->nullable();
            $table->string('buildername', 50)->nullable();
            $table->string('buyeragentaor', 50)->nullable();
            $table->integer('buyeragentbrokerkeynumeric')->nullable();
            $table->string('buyeragentbrokermlsid', 25)->nullable();
            $table->string('buyeragentfirstname', 50)->nullable();
            $table->integer('buyeragentkeynumeric')->nullable();
            $table->string('buyeragentlastname', 50)->nullable();
            $table->integer('buyeragentmainofficekeynumeric')->nullable();
            $table->string('buyeragentmainofficemlsid', 25)->nullable();
            $table->string('buyeragentmlsid', 25)->nullable();
            $table->string('buyeragentstatelicense', 50)->nullable();
            $table->string('buyerofficeaor', 50)->nullable();
            $table->integer('buyerofficekeynumeric')->nullable();
            $table->string('buyerofficemlsid', 25)->nullable();
            $table->text('buyerofficename')->nullable();
            $table->string('buyerofficestatelicense', 50)->nullable();
            $table->string('buyerteamemail', 80)->nullable();
            $table->text('buyerteamkey')->nullable();
            $table->integer('buyerteamkeynumeric')->nullable();
            $table->string('buyerteamname', 50)->nullable();
            $table->string('buyerteampreferredphone', 16)->nullable();
            $table->date('cancellationdate')->nullable();
            $table->decimal('carportspaces',14,2)->nullable();
            $table->boolean('certified433ayn')->nullable();
            $table->string('city', 50)->nullable();
            $table->date('closedate')->nullable();
            $table->decimal('closeprice',14,2)->nullable();
            $table->string('cobuyeragentaor', 50)->nullable();
            $table->integer('cobuyeragentbrokerkeynumeric')->nullable();
            $table->string('cobuyeragentbrokermlsid', 25)->nullable();
            $table->string('cobuyeragentfirstname', 50)->nullable();
            $table->integer('cobuyeragentkeynumeric')->nullable();
            $table->string('cobuyeragentlastname', 50)->nullable();
            $table->integer('cobuyeragentmainofficekeynumeric')->nullable();
            $table->string('cobuyeragentmlsid', 25)->nullable();
            $table->string('cobuyeragentstatelicense', 50)->nullable();
            $table->string('cobuyerofficeaor', 50)->nullable();
            $table->integer('cobuyerofficekeynumeric')->nullable();
            $table->string('cobuyerofficemlsid', 25)->nullable();
            $table->text('cobuyerofficename')->nullable();
            $table->string('cobuyerofficestatelicense', 50)->nullable();
            $table->string('cobuyerteamemail', 80)->nullable();
            $table->text('cobuyerteamkey')->nullable();
            $table->integer('cobuyerteamkeynumeric')->nullable();
            $table->string('cobuyerteamname', 50)->nullable();
            $table->string('cobuyerteampreferredphone', 16)->nullable();
            $table->string('colistagentaor', 50)->nullable();
            $table->string('colistagentfirstname', 50)->nullable();
            $table->integer('colistagentkeynumeric')->nullable();
            $table->string('colistagentlastname', 50)->nullable();
            $table->string('colistagentmlsid', 25)->nullable();
            $table->string('colistagentstatelicense', 50)->nullable();
            $table->string('colistofficeaor', 50)->nullable();
            $table->string('colistofficefax', 16)->nullable();
            $table->integer('colistofficekeynumeric')->nullable();
            $table->string('colistofficemlsid', 25)->nullable();
            $table->text('colistofficename')->nullable();
            $table->string('colistofficephone', 16)->nullable();
            $table->string('colistofficestatelicense', 50)->nullable();
            $table->string('colistteamemail', 80)->nullable();
            $table->text('colistteamkey')->nullable();
            $table->integer('colistteamkeynumeric')->nullable();
            $table->string('colistteamname', 50)->nullable();
            $table->string('colistteampreferredphone', 16)->nullable();
            $table->string('commoninterest', 25)->nullable();
            $table->text('commonwalls')->nullable();
            $table->text('communityfeatures')->nullable();
            $table->text('constructionmaterials')->nullable();
            $table->text('cooling')->nullable();
            $table->boolean('coolingyn')->nullable();
            $table->string('country', 2)->nullable();
            $table->string('countyorparish', 50)->nullable();
            $table->integer('cumulativedaysonmarket')->nullable();
            $table->integer('daysonmarket')->nullable();
            $table->boolean('deletedyn')->nullable();
            $table->string('directionfaces', 25)->nullable();
            $table->text('directions')->nullable();
            $table->string('documentnumber', 50)->nullable();
            $table->string('doh1', 25)->nullable();
            $table->string('doh2', 25)->nullable();
            $table->string('doh3', 25)->nullable();
            $table->text('doorfeatures')->nullable();
            $table->text('eatingarea')->nullable();
            $table->text('electric')->nullable();
            $table->string('elementaryschool', 50)->nullable();
            $table->string('elementaryschool2', 50)->nullable();
            $table->string('elementaryschoolother', 50)->nullable();
            $table->integer('elevation')->nullable();
            $table->integer('entrylevel')->nullable();
            $table->string('entrylocation', 50)->nullable();
            $table->text('exclusions')->nullable();
            $table->text('exteriorfeatures')->nullable();
            $table->boolean('fenceyn')->nullable();
            $table->text('fencing')->nullable();
            $table->text('fireplacefeatures')->nullable();
            $table->boolean('fireplaceyn')->nullable();
            $table->text('flooring')->nullable();
            $table->text('foundationdetails')->nullable();
            $table->decimal('garagespaces',14,2)->nullable();
            $table->text('greenenergyefficient')->nullable();
            $table->text('greenenergygeneration')->nullable();
            $table->text('greenindoorairquality')->nullable();
            $table->text('greenlocation')->nullable();
            $table->text('greensustainability')->nullable();
            $table->text('greenwaterconservation')->nullable();
            $table->text('heating')->nullable();
            $table->boolean('heatingyn')->nullable();
            $table->string('highschool', 50)->nullable();
            $table->string('highschool2', 50)->nullable();
            $table->string('highschooldistrict', 50)->nullable();
            $table->text('inclusions')->nullable();
            $table->text('interiorfeatures')->nullable();
            $table->boolean('internetaddressdisplayyn')->nullable();
            $table->boolean('internetautomatedvaluationdisplayyn')->nullable();
            $table->boolean('internetconsumercommentyn')->nullable();
            $table->boolean('internetentirelistingdisplayyn')->nullable();
            $table->decimal('landleaseamount',14,2)->nullable();
            $table->string('landleaseamountfrequency', 25)->nullable();
            $table->boolean('landleaseyn')->nullable();
            $table->decimal('latitude',12,8)->nullable();
            $table->text('laundryfeatures')->nullable();
            $table->boolean('laundryyn')->nullable();
            $table->boolean('leaseconsideredyn')->nullable();
            $table->text('levels')->nullable();
            $table->string('license1', 25)->nullable();
            $table->string('license2', 25)->nullable();
            $table->string('license3', 25)->nullable();
            $table->string('listagentaor', 50)->nullable();
            $table->string('listagentfirstname', 50)->nullable();
            $table->integer('listagentkeynumeric')->nullable();
            $table->string('listagentlastname', 50)->nullable();
            $table->string('listagentmlsid', 25)->nullable();
            $table->string('listagentstatelicense', 50)->nullable();
            $table->date('listingcontractdate')->nullable();
            $table->text('listingid')->nullable();
            $table->integer('listofficekeynumeric')->nullable();
            $table->string('listofficemlsid', 25)->nullable();
            $table->text('listofficename')->nullable();
            $table->string('listofficestatelicense', 50)->nullable();
            $table->decimal('listprice',14,2)->nullable();
            $table->decimal('listpricelow',14,2)->nullable();
            $table->decimal('livingarea',14,2)->nullable();
            $table->string('livingareasource', 50)->nullable();
            $table->string('livingareaunits', 25)->nullable();
            $table->text('lockboxtype')->nullable();
            $table->text('lockboxversion')->nullable();
            $table->decimal('longitude',12,8)->nullable();
            $table->string('lotdimensionssource', 50)->nullable();
            $table->text('lotfeatures')->nullable();
            $table->decimal('lotsizeacres',16,4)->nullable();
            $table->decimal('lotsizearea',16,4)->nullable();
            $table->text('lotsizedimensions')->nullable();
            $table->string('lotsizesource', 50)->nullable();
            $table->decimal('lotsizesquarefeet',14,2)->nullable();
            $table->string('lotsizeunits', 25)->nullable();
            $table->integer('mainlevelbathrooms')->nullable();
            $table->integer('mainlevelbedrooms')->nullable();
            $table->text('majorchangetype')->nullable();
            $table->string('make', 50)->nullable();
            $table->string('middleorjuniorschool', 50)->nullable();
            $table->string('middleorjuniorschool2', 50)->nullable();
            $table->string('middleorjuniorschoolother', 50)->nullable();
            $table->string('mlsareamajor', 50)->nullable();
            $table->dateTime('modificationtimestamp')->nullable();
            $table->boolean('newconstructionyn')->nullable();
            $table->integer('numberofunitsincommunity')->nullable();
            $table->integer('numberofunitstotal')->nullable();
            $table->integer('numberremotes')->nullable();
            $table->dateTime('offmarkettimestamp')->nullable();
            $table->date('onmarketdate')->nullable();
            $table->dateTime('onmarkettimestamp')->nullable();
            $table->dateTime('originalentrytimestamp')->nullable();
            $table->decimal('originallistprice',14,2)->nullable();
            $table->string('originatingsystemid', 25)->nullable();
            $table->text('originatingsystemkey')->nullable();
            $table->dateTime('originatingsystemmodificationtimestamp')->nullable();
            $table->text('otherstructures')->nullable();
            $table->string('parcelnumber', 50)->nullable();
            $table->text('parkingfeatures')->nullable();
            $table->decimal('parkingtotal',14,2)->nullable();
            $table->boolean('parkingyn')->nullable();
            $table->text('patioandporchfeatures')->nullable();
            $table->boolean('patioyn')->nullable();
            $table->dateTime('photoschangetimestamp')->nullable();
            $table->integer('photoscount')->nullable();
            $table->string('points', 4)->nullable();
            $table->text('poolfeatures')->nullable();
            $table->boolean('poolprivateyn')->nullable();
            $table->string('postalcode', 10)->nullable();
            $table->string('postalcodeplus4', 4)->nullable();
            $table->decimal('previouslistprice',14,2)->nullable();
            $table->string('previousstandardstatus', 25)->nullable();
            $table->decimal('pricepersquarefoot',6,2)->nullable();
            $table->string('probateauthority', 50)->nullable();
            $table->boolean('propertyattachedyn')->nullable();
            $table->text('propertycondition')->nullable();
            $table->string('propertysubtype', 50)->nullable();
            $table->text('publicremarks')->nullable();
            $table->date('purchasecontractdate')->nullable();
            $table->text('roadfrontagetype')->nullable();
            $table->text('roadsurfacetype')->nullable();
            $table->text('roof')->nullable();
            $table->text('roombathroomfeatures')->nullable();
            $table->text('roomkitchenfeatures')->nullable();
            $table->text('roomtype')->nullable();
            $table->string('rvparkingdimensions', 50)->nullable();
            $table->text('securityfeatures')->nullable();
            $table->boolean('seniorcommunityyn')->nullable();
            $table->string('serialu', 25)->nullable();
            $table->string('serialx', 25)->nullable();
            $table->string('serialxx', 25)->nullable();
            $table->text('sewer')->nullable();
            $table->text('spafeatures')->nullable();
            $table->boolean('spayn')->nullable();
            $table->text('speciallistingconditions')->nullable();
            $table->boolean('sprinklersyn')->nullable();
            $table->string('standardstatus', 25)->nullable();
            $table->string('stateorprovince', 2)->nullable();
            $table->dateTime('statuschangetimestamp')->nullable();
            $table->integer('storiestotal')->nullable();
            $table->string('streetdirprefix', 15)->nullable();
            $table->string('streetdirsuffix', 15)->nullable();
            $table->string('streetname', 50)->nullable();
            $table->string('streetnumber', 25)->nullable();
            $table->integer('streetnumbernumeric')->nullable();
            $table->string('streetsuffix', 25)->nullable();
            $table->string('streetsuffixmodifier', 25)->nullable();
            $table->string('subdivisionname', 50)->nullable();
            $table->string('subdivisionnameother', 50)->nullable();
            $table->string('taxcensustract', 25)->nullable();
            $table->string('taxlot', 25)->nullable();
            $table->string('taxmodel', 1)->nullable();
            $table->string('taxtract', 25)->nullable();
            $table->string('taxtractnumber', 6)->nullable();
            $table->string('tractsubareacode', 4)->nullable();
            $table->decimal('uncoveredspaces',14,2)->nullable();
            $table->string('unitnumber', 25)->nullable();
            $table->text('universalpropertyid')->nullable();
            $table->text('utilities')->nullable();
            $table->text('view')->nullable();
            $table->boolean('viewyn')->nullable();
            $table->text('virtualtoururlbranded')->nullable();
            $table->text('virtualtoururlunbranded')->nullable();
            $table->text('virtualtoururlunbranded2')->nullable();
            $table->integer('walkscore')->nullable();
            $table->text('waterfrontfeatures')->nullable();
            $table->text('watersource')->nullable();
            $table->integer('welldepth')->nullable();
            $table->decimal('wellgallonsperminute',6,2)->nullable();
            $table->decimal('wellpumphorsepower',6,2)->nullable();
            $table->boolean('wellreportyn')->nullable();
            $table->text('windowfeatures')->nullable();
            $table->integer('yearbuilt')->nullable();
            $table->string('yearbuiltsource', 60)->nullable();
            $table->string('zoning', 25)->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('residentials');
    }
}
