<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateResidentialsTable extends Migration
{

    protected $primaryKey = 'listingkeynumeric';

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('residentials', function (Blueprint $table) {
            $table->integer('listingkeynumeric');
            $table->text('accessibilityfeatures')->nullable();
            $table->text('additionalparcelsdescription')->nullable();
            $table->boolean('additionalparcelsyn')->nullable();
            $table->char('adnumber', 15)->nullable();
            $table->text('appliances')->nullable();
            $table->boolean('appliancesyn')->nullable();
            $table->text('architecturalstyle')->nullable();
            $table->char('assessments', 68)->nullable();
            $table->boolean('assessmentsyn')->nullable();
            $table->text('associationamenities')->nullable();
            $table->decimal('associationfee',14,2)->nullable();
            $table->decimal('associationfee2',14,2)->nullable();
            $table->char('associationfee2frequency', 25)->nullable();
            $table->char('associationfeefrequency', 25)->nullable();
            $table->char('associationmanagementname', 50)->nullable();
            $table->char('associationmanagementname2', 50)->nullable();
            $table->char('associationname', 50)->nullable();
            $table->char('associationname2', 50)->nullable();
            $table->boolean('associationyn')->nullable();
            $table->boolean('attachedgarageyn')->nullable();
            $table->text('basement')->nullable();
            $table->integer('bathroomsfull')->nullable();
            $table->integer('bathroomsfullandthreequarter')->nullable();
            $table->integer('bathroomshalf')->nullable();
            $table->integer('bathroomsonequarter')->nullable();
            $table->integer('bathroomsthreequarter')->nullable();
            $table->integer('bathroomstotalinteger')->nullable();
            $table->integer('bedroomstotal')->nullable();
            $table->decimal('belowgradefinishedarea',14,2)->nullable();
            $table->char('belowgradefinishedareaunits', 25)->nullable();
            $table->char('buildermodel', 50)->nullable();
            $table->char('buildername', 50)->nullable();
            $table->char('buyeragentaor', 50)->nullable();
            $table->integer('buyeragentbrokerkeynumeric')->nullable();
            $table->char('buyeragentbrokermlsid', 25)->nullable();
            $table->char('buyeragentfirstname', 50)->nullable();
            $table->integer('buyeragentkeynumeric')->nullable();
            $table->char('buyeragentlastname', 50)->nullable();
            $table->integer('buyeragentmainofficekeynumeric')->nullable();
            $table->char('buyeragentmainofficemlsid', 25)->nullable();
            $table->char('buyeragentmlsid', 25)->nullable();
            $table->char('buyeragentstatelicense', 50)->nullable();
            $table->char('buyerofficeaor', 50)->nullable();
            $table->integer('buyerofficekeynumeric')->nullable();
            $table->char('buyerofficemlsid', 25)->nullable();
            $table->text('buyerofficename')->nullable();
            $table->char('buyerofficestatelicense', 50)->nullable();
            $table->char('buyerteamemail', 80)->nullable();
            $table->text('buyerteamkey')->nullable();
            $table->integer('buyerteamkeynumeric')->nullable();
            $table->char('buyerteamname', 50)->nullable();
            $table->char('buyerteampreferredphone', 16)->nullable();
            $table->date('cancellationdate')->nullable();
            $table->decimal('carportspaces',14,2)->nullable();
            $table->boolean('certified433ayn')->nullable();
            $table->char('city', 50)->nullable();
            $table->date('closedate')->nullable();
            $table->decimal('closeprice',14,2)->nullable();
            $table->char('cobuyeragentaor', 50)->nullable();
            $table->integer('cobuyeragentbrokerkeynumeric')->nullable();
            $table->char('cobuyeragentbrokermlsid', 25)->nullable();
            $table->char('cobuyeragentfirstname', 50)->nullable();
            $table->integer('cobuyeragentkeynumeric')->nullable();
            $table->char('cobuyeragentlastname', 50)->nullable();
            $table->integer('cobuyeragentmainofficekeynumeric')->nullable();
            $table->char('cobuyeragentmlsid', 25)->nullable();
            $table->char('cobuyeragentstatelicense', 50)->nullable();
            $table->char('cobuyerofficeaor', 50)->nullable();
            $table->integer('cobuyerofficekeynumeric')->nullable();
            $table->char('cobuyerofficemlsid', 25)->nullable();
            $table->text('cobuyerofficename')->nullable();
            $table->char('cobuyerofficestatelicense', 50)->nullable();
            $table->char('cobuyerteamemail', 80)->nullable();
            $table->text('cobuyerteamkey')->nullable();
            $table->integer('cobuyerteamkeynumeric')->nullable();
            $table->char('cobuyerteamname', 50)->nullable();
            $table->char('cobuyerteampreferredphone', 16)->nullable();
            $table->char('colistagentaor', 50)->nullable();
            $table->char('colistagentfirstname', 50)->nullable();
            $table->integer('colistagentkeynumeric')->nullable();
            $table->char('colistagentlastname', 50)->nullable();
            $table->char('colistagentmlsid', 25)->nullable();
            $table->char('colistagentstatelicense', 50)->nullable();
            $table->char('colistofficeaor', 50)->nullable();
            $table->char('colistofficefax', 16)->nullable();
            $table->integer('colistofficekeynumeric')->nullable();
            $table->char('colistofficemlsid', 25)->nullable();
            $table->text('colistofficename')->nullable();
            $table->char('colistofficephone', 16)->nullable();
            $table->char('colistofficestatelicense', 50)->nullable();
            $table->char('colistteamemail', 80)->nullable();
            $table->text('colistteamkey')->nullable();
            $table->integer('colistteamkeynumeric')->nullable();
            $table->char('colistteamname', 50)->nullable();
            $table->char('colistteampreferredphone', 16)->nullable();
            $table->char('commoninterest', 25)->nullable();
            $table->text('commonwalls')->nullable();
            $table->text('communityfeatures')->nullable();
            $table->text('constructionmaterials')->nullable();
            $table->text('cooling')->nullable();
            $table->boolean('coolingyn')->nullable();
            $table->char('country', 2)->nullable();
            $table->char('countyorparish', 50)->nullable();
            $table->integer('cumulativedaysonmarket')->nullable();
            $table->integer('daysonmarket')->nullable();
            $table->boolean('deletedyn')->nullable();
            $table->char('directionfaces', 25)->nullable();
            $table->text('directions')->nullable();
            $table->char('documentnumber', 50)->nullable();
            $table->char('doh1', 25)->nullable();
            $table->char('doh2', 25)->nullable();
            $table->char('doh3', 25)->nullable();
            $table->text('doorfeatures')->nullable();
            $table->text('eatingarea')->nullable();
            $table->text('electric')->nullable();
            $table->char('elementaryschool', 50)->nullable();
            $table->char('elementaryschool2', 50)->nullable();
            $table->char('elementaryschoolother', 50)->nullable();
            $table->integer('elevation')->nullable();
            $table->integer('entrylevel')->nullable();
            $table->char('entrylocation', 50)->nullable();
            $table->text('exclusions')->nullable();
            $table->text('exteriorfeatures')->nullable();
            $table->boolean('fenceyn')->nullable();
            $table->text('fencing')->nullable();
            $table->text('fireplacefeatures')->nullable();
            $table->boolean('fireplaceyn')->nullable();
            $table->text('flooring')->nullable();
            $table->text('foundationdetails')->nullable();
            $table->decimal('garagespaces',14,2)->nullable();
            $table->text('greenenergyefficient')->nullable();
            $table->text('greenenergygeneration')->nullable();
            $table->text('greenindoorairquality')->nullable();
            $table->text('greenlocation')->nullable();
            $table->text('greensustainability')->nullable();
            $table->text('greenwaterconservation')->nullable();
            $table->text('heating')->nullable();
            $table->boolean('heatingyn')->nullable();
            $table->char('highschool', 50)->nullable();
            $table->char('highschool2', 50)->nullable();
            $table->char('highschooldistrict', 50)->nullable();
            $table->text('inclusions')->nullable();
            $table->text('interiorfeatures')->nullable();
            $table->boolean('internetaddressdisplayyn')->nullable();
            $table->boolean('internetautomatedvaluationdisplayyn')->nullable();
            $table->boolean('internetconsumercommentyn')->nullable();
            $table->boolean('internetentirelistingdisplayyn')->nullable();
            $table->decimal('landleaseamount',14,2)->nullable();
            $table->char('landleaseamountfrequency', 25)->nullable();
            $table->boolean('landleaseyn')->nullable();
            $table->decimal('latitude',12,8)->nullable();
            $table->text('laundryfeatures')->nullable();
            $table->boolean('laundryyn')->nullable();
            $table->boolean('leaseconsideredyn')->nullable();
            $table->text('levels')->nullable();
            $table->char('license1', 25)->nullable();
            $table->char('license2', 25)->nullable();
            $table->char('license3', 25)->nullable();
            $table->char('listagentaor', 50)->nullable();
            $table->char('listagentfirstname', 50)->nullable();
            $table->integer('listagentkeynumeric')->nullable();
            $table->char('listagentlastname', 50)->nullable();
            $table->char('listagentmlsid', 25)->nullable();
            $table->char('listagentstatelicense', 50)->nullable();
            $table->date('listingcontractdate')->nullable();
            $table->text('listingid')->nullable();
            $table->integer('listofficekeynumeric')->nullable();
            $table->char('listofficemlsid', 25)->nullable();
            $table->text('listofficename')->nullable();
            $table->char('listofficestatelicense', 50)->nullable();
            $table->decimal('listprice',14,2)->nullable();
            $table->decimal('listpricelow',14,2)->nullable();
            $table->decimal('livingarea',14,2)->nullable();
            $table->char('livingareasource', 50)->nullable();
            $table->char('livingareaunits', 25)->nullable();
            $table->text('lockboxtype')->nullable();
            $table->text('lockboxversion')->nullable();
            $table->decimal('longitude',12,8)->nullable();
            $table->char('lotdimensionssource', 50)->nullable();
            $table->text('lotfeatures')->nullable();
            $table->decimal('lotsizeacres',16,4)->nullable();
            $table->decimal('lotsizearea',16,4)->nullable();
            $table->text('lotsizedimensions')->nullable();
            $table->char('lotsizesource', 50)->nullable();
            $table->decimal('lotsizesquarefeet',14,2)->nullable();
            $table->char('lotsizeunits', 25)->nullable();
            $table->integer('mainlevelbathrooms')->nullable();
            $table->integer('mainlevelbedrooms')->nullable();
            $table->text('majorchangetype')->nullable();
            $table->char('make', 50)->nullable();
            $table->char('middleorjuniorschool', 50)->nullable();
            $table->char('middleorjuniorschool2', 50)->nullable();
            $table->char('middleorjuniorschoolother', 50)->nullable();
            $table->char('mlsareamajor', 50)->nullable();
            $table->dateTime('modificationtimestamp')->nullable();
            $table->boolean('newconstructionyn')->nullable();
            $table->integer('numberofunitsincommunity')->nullable();
            $table->integer('numberofunitstotal')->nullable();
            $table->integer('numberremotes')->nullable();
            $table->dateTime('offmarkettimestamp')->nullable();
            $table->date('onmarketdate')->nullable();
            $table->dateTime('onmarkettimestamp')->nullable();
            $table->dateTime('originalentrytimestamp')->nullable();
            $table->decimal('originallistprice',14,2)->nullable();
            $table->char('originatingsystemid', 25)->nullable();
            $table->text('originatingsystemkey')->nullable();
            $table->dateTime('originatingsystemmodificationtimestamp')->nullable();
            $table->text('otherstructures')->nullable();
            $table->char('parcelnumber', 50)->nullable();
            $table->text('parkingfeatures')->nullable();
            $table->decimal('parkingtotal',14,2)->nullable();
            $table->boolean('parkingyn')->nullable();
            $table->text('patioandporchfeatures')->nullable();
            $table->boolean('patioyn')->nullable();
            $table->dateTime('photoschangetimestamp')->nullable();
            $table->integer('photoscount')->nullable();
            $table->char('points', 4)->nullable();
            $table->text('poolfeatures')->nullable();
            $table->boolean('poolprivateyn')->nullable();
            $table->char('postalcode', 10)->nullable();
            $table->char('postalcodeplus4', 4)->nullable();
            $table->decimal('previouslistprice',14,2)->nullable();
            $table->char('previousstandardstatus', 25)->nullable();
            $table->decimal('pricepersquarefoot',6,2)->nullable();
            $table->char('probateauthority', 50)->nullable();
            $table->boolean('propertyattachedyn')->nullable();
            $table->text('propertycondition')->nullable();
            $table->char('propertysubtype', 50)->nullable();
            $table->text('publicremarks')->nullable();
            $table->date('purchasecontractdate')->nullable();
            $table->text('roadfrontagetype')->nullable();
            $table->text('roadsurfacetype')->nullable();
            $table->text('roof')->nullable();
            $table->text('roombathroomfeatures')->nullable();
            $table->text('roomkitchenfeatures')->nullable();
            $table->text('roomtype')->nullable();
            $table->char('rvparkingdimensions', 50)->nullable();
            $table->text('securityfeatures')->nullable();
            $table->boolean('seniorcommunityyn')->nullable();
            $table->char('serialu', 25)->nullable();
            $table->char('serialx', 25)->nullable();
            $table->char('serialxx', 25)->nullable();
            $table->text('sewer')->nullable();
            $table->text('spafeatures')->nullable();
            $table->boolean('spayn')->nullable();
            $table->text('speciallistingconditions')->nullable();
            $table->boolean('sprinklersyn')->nullable();
            $table->char('standardstatus', 25)->nullable();
            $table->char('stateorprovince', 2)->nullable();
            $table->dateTime('statuschangetimestamp')->nullable();
            $table->integer('storiestotal')->nullable();
            $table->char('streetdirprefix', 15)->nullable();
            $table->char('streetdirsuffix', 15)->nullable();
            $table->char('streetname', 50)->nullable();
            $table->char('streetnumber', 25)->nullable();
            $table->integer('streetnumbernumeric')->nullable();
            $table->char('streetsuffix', 25)->nullable();
            $table->char('streetsuffixmodifier', 25)->nullable();
            $table->char('subdivisionname', 50)->nullable();
            $table->char('subdivisionnameother', 50)->nullable();
            $table->char('taxcensustract', 25)->nullable();
            $table->char('taxlot', 25)->nullable();
            $table->char('taxmodel', 1)->nullable();
            $table->char('taxtract', 25)->nullable();
            $table->char('taxtractnumber', 6)->nullable();
            $table->char('tractsubareacode', 4)->nullable();
            $table->decimal('uncoveredspaces',14,2)->nullable();
            $table->char('unitnumber', 25)->nullable();
            $table->text('universalpropertyid')->nullable();
            $table->text('utilities')->nullable();
            $table->text('view')->nullable();
            $table->boolean('viewyn')->nullable();
            $table->text('virtualtoururlbranded')->nullable();
            $table->text('virtualtoururlunbranded')->nullable();
            $table->text('virtualtoururlunbranded2')->nullable();
            $table->integer('walkscore')->nullable();
            $table->text('waterfrontfeatures')->nullable();
            $table->text('watersource')->nullable();
            $table->integer('welldepth')->nullable();
            $table->decimal('wellgallonsperminute',6,2)->nullable();
            $table->decimal('wellpumphorsepower',6,2)->nullable();
            $table->boolean('wellreportyn')->nullable();
            $table->text('windowfeatures')->nullable();
            $table->integer('yearbuilt')->nullable();
            $table->char('yearbuiltsource', 60)->nullable();
            $table->char('zoning', 25)->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('residentials');
    }
}
